---
server:
  port: 8888
spring:
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/Puneethkumarck/spring-cloud-config-test.git # default
          search-paths:
            - 'station*'

  profile:
    active: dev