---
server:
  port: 8888
spring:
  cloud:
    config:
      server:
        encrypt:

        git:
          uri: https://github.com/Puneethkumarck/spring-cloud-config-test.git # default
          search-paths:
            - 'station*'
          repos:
              local:
                 pattern: '*/local'
                 uri: https://github.com/Puneethkumarck/spring-cloud-config-test.git # alt
                 search-paths:
                  - 'station*'

security:
  basic:
    enabled: true
  user:
    name: work@home
    password: work@home